project:
  type: website
  output-dir: docs

website:
  title: "Alberto Guzman-Alvarez, Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css



