project:
  type: website
  output-dir: docs

website:
  title: "Alberto Guzman-Alvarez, Ph.D."
  navbar:
    background: primary
    left:
      - href: https://github.com/alberto-guzman/alberto-guzman.github.io/blob/master/Alberto%20Guzman-Alvarez%20CV%200323.pdf
        text: CV
      - icon: github
        href: https://github.com/alberto-guzman
      - resources.qmd



format:
  html:
    theme: darkly
    css: styles.css

    