project:
  type: website
  output-dir: docs

website:
  title: "Alberto Guzman-Alvarez, Ph.D."
  navbar:
    right:
      - text: CV
        href: https://github.com/alberto-guzman/alberto-guzman.github.io/blob/master/Alberto%20Guzman-Alvarez%20CV%200323.pdf
      - icon: twitter
        href: https://twitter.com/AlbertoGuzAlv
      - icon: github
        href: https://github.com/alberto-guzman

format:
  html:
    theme: lux
    css: styles.css
    



